from planfix_mcp.limit import Profile

type FieldSet = dict[Profile, tuple[str, ...]]

GENERIC: FieldSet = {
    'schema': ('ID', 'Title', 'Name'),
    'summary': (
        'ID',
        'Title',
        'Name',
        'GeneralID',
        'Status',
        'StatusText',
        'Owner',
        'Type',
        'Login',
        'Project',
        'Description',
        'User',
        'DateTime',
        'Group',
        'Client',
        'IsPublic',
        'IsActive',
    ),
    'detail': (
        'ID',
        'Title',
        'Name',
        'GeneralID',
        'Status',
        'StatusText',
        'Owner',
        'Type',
        'Login',
        'Project',
        'Description',
        'User',
        'DateTime',
        'Group',
        'Client',
        'IsPublic',
        'IsActive',
        'Parent',
        'BeginDateTime',
        'EndTime',
        'HasEndDate',
        'IsSystem',
        'IsEditable',
    ),
}
# Date + author + type + event text. Planfix log rows use mixed key casings;
# normalize_log_item maps them onto these names before pick.
_LOG: FieldSet = {
    'schema': ('ID', 'DateTime', 'Type', 'Description'),
    'summary': ('ID', 'DateTime', 'Type', 'User', 'Description'),
    'detail': (
        'ID',
        'DateTime',
        'Type',
        'User',
        'Description',
        'Action',
        'Task',
        'Project',
        'Data',
    ),
}


def _levels(
    schema: tuple[str, ...],
    summary: tuple[str, ...],
    extra: tuple[str, ...] = (),
) -> FieldSet:
    detail = (*summary, *(name for name in extra if name not in summary))
    return {'schema': schema, 'summary': summary, 'detail': detail}


_TASK_ROW = _levels(
    ('ID', 'Title'),
    (
        'ID',
        'GeneralID',
        'General',
        'Title',
        'Status',
        'StatusText',
        'Owner',
        'Project',
        'Parent',
        'BeginDateTime',
        'EndTime',
        'HasEndDate',
        'DateDone',
        'IsOverdued',
        'DeadlineStatus',
        'WorkersList',
        'ActionsCount',
    ),
    (
        'Client',
        'MembersList',
        'AuditorsList',
        'StatusSetID',
        'Importance',
        'FilesCount',
        'DateCompleted',
        'DateOfLastAction',
        'SubTasksCount',
        'TemplateID',
        'IsTemplate',
        'IsCRM',
        'HasChilds',
        'Starred',
    ),
)
_PROJECT_ROW = _levels(
    ('ID', 'Title'),
    (
        'ID',
        'GeneralID',
        'Title',
        'Status',
        'StatusText',
        'Owner',
        'Client',
        'Parent',
        'BeginDate',
        'BeginDateTime',
        'EndDate',
        'EndTime',
        'HasEndDate',
        'DeadlineStatus',
        'TaskCount',
    ),
    (
        'Group',
        'ManagersList',
        'WorkersList',
        'AuditorsList',
        'TaskTemplateID',
        'PlannerID',
        'IsTemplate',
        'Starred',
        'SubProjectsCount',
        'HasSubprojects',
    ),
)
_CONTACT_ROW = _levels(
    ('ID', 'Title'),
    (
        'ID',
        'GeneralID',
        'Title',
        'Type',
        'Owner',
        'StatusSetID',
        'StatusSetName',
        'IsCRM',
        'TemplateID',
        'TemplateObject',
        'BeginDateTime',
        'contact',
    ),
    ('WorkersList', 'MembersList', 'AuditorsList', 'workSpace', 'IsTemplate'),
)
_EMPLOYEE_ROW = _levels(
    ('ID', 'Name'),
    (
        'ID',
        'Name',
        'GeneralID',
        'Login',
        'GroupsList',
        'RoleText',
        'Role',
        'IsAccountOwner',
        'IsSystemRobot',
        'workSpace',
    ),
    ('WorkHours', 'Post', 'Description', 'UserIsDeleted'),
)
_PLANNER_ROW = _levels(
    ('ID', 'Name'),
    (
        'ID',
        'Name',
        'GroupID',
        'Login',
        'IsPublic',
        'IsDefault',
        'Hidden',
        'Color',
        'TaskFilterID',
        'IsEditable',
        'IsSync',
    ),
    ('IsPublicForClients', 'PlannerNeedNoAccess', 'MenuIconId', 'isGroup', 'UserName'),
)

ITEM_FIELDS: dict[tuple[str, str], FieldSet] = {
    ('tasks', 'list'): _TASK_ROW,
    ('tasks', 'global_search'): _TASK_ROW,
    ('tasks', 'search_actions'): _levels(
        ('ID', 'DateTime', 'Type'),
        ('ID', 'DateTime', 'Type', 'User', 'Description', 'OldStatus', 'NewStatus', 'Task'),
        ('IsHidden', 'IsDeleted', 'Files', 'Project'),
    ),
    ('projects', 'list'): _PROJECT_ROW,
    ('projects', 'global_search'): _PROJECT_ROW,
    ('projects', 'templates'): _levels(
        ('ID', 'Title'),
        ('ID', 'Title', 'IsObject', 'IsTemplate'),
        ('Owner', 'Status'),
    ),
    ('contacts', 'list'): _CONTACT_ROW,
    ('contacts', 'global_search'): _CONTACT_ROW,
    ('contacts', 'client_search'): _CONTACT_ROW,
    ('contacts', 'templates'): _levels(
        ('ID', 'Title'),
        ('ID', 'Title', 'IsObject', 'IsTemplate'),
        ('Owner', 'StatusSetID'),
    ),
    ('employees', 'list'): _EMPLOYEE_ROW,
    ('employees', 'global_search'): _EMPLOYEE_ROW,
    ('employees', 'groups'): _levels(
        ('ID', 'Name'),
        ('ID', 'Name', 'UserCount', 'IsSystem', 'HeadsAreEqual'),
        ('OrgtreeTop', 'OrgtreeLeft', 'IsPublicForUsers', 'IsPublicForContacts'),
    ),
    ('handbooks', 'list'): _levels(
        ('ID', 'Name'),
        ('ID', 'Name', 'Type', 'Group', 'Owner', 'IsPublic'),
        ('Description', 'ColumnsCount'),
    ),
    ('filters', 'all'): _levels(
        ('ID', 'Name', 'Type'),
        (
            'ID',
            'Name',
            'Type',
            'IsPublic',
            'IsSystem',
            'IsEditable',
            'DefaultView',
            'Mode',
            'GroupID',
            'Logic',
            'objectId',
            'HandbookId',
            'IsOnPanel',
        ),
        ('Cases', 'GroupBy', 'Sort', 'PlannerID', 'Columns', 'KanbanFields'),
    ),
    ('analytics', 'list'): _levels(
        ('ID', 'Name', 'Group'),
        ('ID', 'Name', 'Group', 'IsActive', 'IsSystem', 'Key', 'Fields'),
        ('HasReadRestrictions', 'HasWriteRestrictions', 'Layout'),
    ),
    ('reports', 'list'): _levels(
        ('ID', 'Name', 'Group'),
        ('ID', 'Name', 'Group', 'Description', 'Starred', 'ObjectType', 'IsEditable'),
        ('DefaultFilters', 'DefaultGroupbys', 'Analitics', 'TaskIsShown', 'Handbook', 'Periodicity'),
    ),
    ('account_config', 'task_templates'): _levels(
        ('ID', 'Title', 'IsObject'),
        ('ID', 'Title', 'IsObject', 'CreateTitle', 'StatusSetID', 'Parent'),
        ('IsTemplate', 'IsSystemTemplate', 'Owner'),
    ),
    ('account_config', 'custom_fields'): _levels(
        ('ID', 'Name', 'Type'),
        ('ID', 'Name', 'Type', 'Group', 'IsSystem', 'IsEditable', 'ObjectType', 'HandbookID'),
        ('Comment', 'EnumValues', 'Flags', 'DefaultValue', 'IsCreated'),
    ),
    ('automation', 'status_sets'): _levels(
        ('ID', 'Name'),
        (
            'ID',
            'Name',
            'CommentsAllowed',
            'AutoAccept',
            'ObjectType',
            'IsForObject',
            'TaskObjectID',
            'PlannerID',
            'PlanerID',
        ),
        ('ObjectListGroupID', 'statusSetParams'),
    ),
    ('automation', 'triggers'): _levels(
        ('ID', 'Name', 'EventType', 'IsActive'),
        ('ID', 'Name', 'EventType', 'Description', 'IsActive', 'StatusSetID'),
        ('Order', 'Conditions'),
    ),
    ('automation', 'macros'): _levels(
        ('ID', 'Name'),
        ('ID', 'Name', 'ObjectType', 'Description', 'IsActive'),
        ('StatusSetID', 'Order'),
    ),
    ('tasks', 'tech_log'): _LOG,
    ('audit', 'entity_log'): _LOG,
    ('audit', 'user_log'): _LOG,
    ('documents', 'items'): _levels(
        ('ID', 'Name', 'Title'),
        ('ID', 'Name', 'Title', 'Type', 'Folder', 'Size', 'Owner', 'DateTime'),
        ('Extension', 'Task', 'Project', 'IsFolder'),
    ),
    ('planners', 'all'): _PLANNER_ROW,
    ('planners', 'list'): _PLANNER_ROW,
    ('account_config', 'incoming_webhooks'): {
        'schema': ('id', 'name'),
        'summary': ('id', 'name', 'requestType', 'method', 'isActive'),
        'detail': (
            'id',
            'name',
            'requestType',
            'method',
            'isActive',
            'actionsLoginType',
            'actionsLoginId',
            'withoutNotices',
            'responseType',
            'deleted',
        ),
        'full': (
            'id',
            'name',
            'requestType',
            'method',
            'isActive',
            'actionsLoginType',
            'actionsLoginId',
            'withoutNotices',
            'responseType',
            'deleted',
        ),
    },
}

CARD = _levels(
    ('ID', 'Title', 'Status'),
    (
        'ID',
        'GeneralID',
        'Title',
        'Description',
        'Status',
        'StatusText',
        'StatusSetID',
        'StatusSetName',
        'Importance',
        'ImportanceText',
        'Owner',
        'Project',
        'Parent',
        'Client',
        'BeginDateTime',
        'EndTime',
        'HasEndDate',
        'HasStartDate',
        'DateDone',
        'DateCompleted',
        'IsOverdued',
        'DeadlineStatus',
        'WorkersList',
        'MembersList',
        'AuditorsList',
        'ActionsCount',
        'FilesCount',
        'TemplateID',
        'TemplateTitle',
    ),
    (
        'Assignee',
        'CustomFields',
        'Periodicity',
        'IsObject',
        'ObjectID',
        'Duration',
        'DurationText',
        'SubTasksCount',
        'Starred',
        'IsEditable',
        'IsWorker',
        'IsCRM',
        'ActivationDate',
        'DateOfLastAction',
        'statusesForChangeList',
    ),
)
ACTION = _levels(
    ('ID', 'DateTime', 'Type'),
    (
        'ID',
        'DateTime',
        'Type',
        'User',
        'Description',
        'OldStatus',
        'NewStatus',
        'IsHidden',
        'IsDeleted',
        'Files',
    ),
    ('IsAttached', 'Task', 'OriginalDateTime', 'Starred', 'NotifiedLogins', 'AnaliticList', 'WorkDate'),
)
